# Generated by Django 4.2.15 on 2024-08-12 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import ptkr.models.ptkr


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bencana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_bencana', models.CharField(choices=[('Gempa Bumi', 'Gempa Bumi'), ('Banjir', 'Banjir'), ('Topan', 'Topan'), ('Kebakaran', 'Kebakaran'), ('Tanah Bergerak', 'Tanah Bergerak'), ('Tanah Longsor', 'Tanah Longsor')], max_length=50, verbose_name='Jenis bencana')),
                ('tanggal_terjadi', models.DateField(verbose_name='Tanggal terjadi')),
                ('deskripsi', models.TextField(max_length=1000, verbose_name='Deskripsi bencana')),
            ],
            options={
                'verbose_name': 'Bencana',
                'verbose_name_plural': 'Bencana',
            },
        ),
        migrations.CreateModel(
            name='Shp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Peta')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Deskripsi')),
                ('file', models.FileField(upload_to='%Y/%m/%d', verbose_name='Unggah Berkas')),
                ('uploaded_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Tanggal Unggah')),
            ],
            options={
                'verbose_name_plural': 'Shape Files',
            },
        ),
        migrations.CreateModel(
            name='RumahTerdampak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemilik_rumah', models.CharField(max_length=60, verbose_name='Pemilik rumah')),
                ('tipe_bangunan', models.CharField(max_length=50, verbose_name='Tipe bangunan rumah')),
                ('provinsi', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('kota', models.CharField(max_length=100, verbose_name='Kota')),
                ('kecamatan', models.CharField(max_length=100, verbose_name='Kecamatan')),
                ('kelurahan', models.CharField(max_length=100, verbose_name='Kelurahan')),
                ('dusun', models.CharField(max_length=100, verbose_name='Dusun')),
                ('rw', models.CharField(max_length=3, verbose_name='RW')),
                ('rt', models.CharField(max_length=3, verbose_name='RT')),
                ('foto', models.ImageField(upload_to=ptkr.models.ptkr.RumahTerdampak.file_upload, verbose_name='Foto sample')),
                ('ket_pondasi', models.CharField(max_length=150, verbose_name='Indikasi kerusakan pondasi')),
                ('ket_kolom', models.CharField(max_length=150, verbose_name='Indikasi kerusakan kolom')),
                ('ket_balok', models.CharField(max_length=150, verbose_name='Indikasi kerusakan balok')),
                ('ket_atap', models.CharField(max_length=150, verbose_name='Indikasi kerusakan atap')),
                ('ket_dinding', models.CharField(max_length=150, verbose_name='Indikasi kerusakan dinding')),
                ('tingkat_kerusakan', models.CharField(max_length=20, verbose_name='Tingkat kerusakan')),
                ('bencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bencana', to='ptkr.bencana', verbose_name='Bencana')),
            ],
            options={
                'verbose_name': 'Rumah Terdampak',
                'verbose_name_plural': 'Rumah Terdampak',
            },
        ),
    ]
