# Generated by Django 4.2.15 on 2024-09-08 15:13

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import ptkr.models.ptkr


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bencana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_bencana', models.CharField(choices=[('Gempa Bumi', 'Gempa Bumi'), ('Banjir', 'Banjir'), ('Topan', 'Topan'), ('Kebakaran', 'Kebakaran'), ('Tanah Bergerak', 'Tanah Bergerak'), ('Tanah Longsor', 'Tanah Longsor')], max_length=50, verbose_name='Jenis bencana')),
                ('tanggal_terjadi', models.DateTimeField(verbose_name='Tanggal terjadi')),
                ('lokasi_bencana', models.CharField(choices=[('Batursari', 'Batursari'), ('Benda', 'Benda'), ('Buniwah', 'Buniwah'), ('Dawuhan', 'Dawuhan'), ('Igirklanceng', 'Igirklanceng'), ('Kaligiri', 'Kaligiri'), ('Kaliloka', 'Kaliloka'), ('Manggis', 'Manggis'), ('Mendala', 'Mendala'), ('Mlayang', 'Mlayang'), ('Plompong', 'Plompong'), ('Sridadi', 'Sridadi'), ('Wanareja', 'Wanareja')], max_length=50, verbose_name='Desa Tempat Bencana Terjadi')),
                ('deskripsi', models.TextField(blank=True, help_text='Opsional, boleh diisi boleh tidak.', max_length=1000, null=True, verbose_name='Deskripsi bencana')),
            ],
            options={
                'verbose_name': 'Bencana',
                'verbose_name_plural': 'Bencana',
            },
        ),
        migrations.CreateModel(
            name='Shp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Peta')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Deskripsi')),
                ('file', models.FileField(upload_to='%Y/%m/%d', verbose_name='Unggah Berkas')),
                ('uploaded_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Tanggal Unggah')),
            ],
            options={
                'verbose_name_plural': 'Shape Files',
            },
        ),
        migrations.CreateModel(
            name='Bangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemilik_rumah', models.CharField(max_length=60, verbose_name='Pemilik rumah')),
                ('tipe_bangunan', models.CharField(max_length=50, verbose_name='Tipe bangunan rumah')),
                ('provinsi', models.CharField(max_length=150, verbose_name='Provinsi')),
                ('kota', models.CharField(max_length=150, verbose_name='Kota')),
                ('kecamatan', models.CharField(max_length=150, verbose_name='Kecamatan')),
                ('kelurahan', models.CharField(max_length=150, verbose_name='Kelurahan')),
                ('dusun', models.CharField(max_length=150, verbose_name='Dusun')),
                ('rw', models.CharField(max_length=3, verbose_name='RW')),
                ('rt', models.CharField(max_length=3, verbose_name='RT')),
                ('foto', models.ImageField(help_text='Ukuran foto maksimal 5MB.', upload_to=ptkr.models.ptkr.Bangunan.file_upload, validators=[ptkr.models.ptkr.file_size, ptkr.models.ptkr.file_extension], verbose_name='Foto Rumah')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('long', models.FloatField(verbose_name='Longitude')),
                ('publish', models.DateField(auto_now_add=True, verbose_name='Tanggal diunggah')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Titik Koordinat Lokasi Rumah')),
                ('ket_pondasi', models.CharField(max_length=255, verbose_name='Indikasi kerusakan pondasi')),
                ('pondasi', models.FloatField(verbose_name='Tingkat Kerusakan Pondasi')),
                ('ket_kolom', models.CharField(max_length=255, verbose_name='Indikasi kerusakan kolom')),
                ('kolom', models.FloatField(verbose_name='Tingkat Kerusakan Kolom')),
                ('ket_balok', models.CharField(max_length=255, verbose_name='Indikasi kerusakan balok')),
                ('balok', models.FloatField(verbose_name='Tingkat Kerusakan Balok')),
                ('ket_plantai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indikasi kerusakan plat lantai')),
                ('plat_lantai', models.FloatField(blank=True, null=True, verbose_name='Tingkat Kerusakan Plat Lantai')),
                ('ket_tangga', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indikasi kerusakan tangga')),
                ('tangga', models.FloatField(blank=True, null=True, verbose_name='Tingkat Kerusakan Tangga')),
                ('ket_atap', models.CharField(max_length=255, verbose_name='Indikasi kerusakan atap')),
                ('atap', models.FloatField(verbose_name='Tingkat Kerusakan Atap')),
                ('ket_dinding', models.CharField(max_length=255, verbose_name='Indikasi kerusakan dinding')),
                ('dinding', models.FloatField(verbose_name='Tingkat Kerusakan Dinding')),
                ('plafon', models.FloatField(verbose_name='Tingkat Kerusakan Plafon')),
                ('lantai', models.FloatField(verbose_name='Tingkat Kerusakan Lantai')),
                ('kusen', models.FloatField(verbose_name='Tingkat Kerusakan Kusen')),
                ('pintu', models.FloatField(verbose_name='Tingkat Kerusakan Pintu')),
                ('jendela', models.FloatField(verbose_name='Tingkat Kerusakan Jendela')),
                ('f_plafon', models.FloatField(verbose_name='Tingkat Kerusakan Finishing Plafon')),
                ('f_dinding', models.FloatField(verbose_name='Tingkat Kerusakan Finishing Dinding')),
                ('f_kusen_pintu', models.FloatField(verbose_name='Tingkat Kerusakan Finishing Kusen & Pintu')),
                ('instalasi_listrik', models.FloatField(verbose_name='Tingkat Kerusakan Instalasi Listrik')),
                ('instalasi_air_bersih', models.FloatField(verbose_name='Tingkat Kerusakan Instalasi Air Bersih')),
                ('drainase_limbah', models.FloatField(verbose_name='Tingkat Kerusakan Drainase Limbah')),
                ('tingkat_kerusakan', models.CharField(max_length=20, verbose_name='Tingkat kerusakan')),
                ('bencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rumah_terdampak', to='ptkr.bencana', verbose_name='Bencana')),
            ],
            options={
                'verbose_name': 'Bangunan Terdampak',
                'verbose_name_plural': 'Bangunan Terdampak',
            },
        ),
    ]
