# Generated by Django 4.2.15 on 2024-08-08 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Peta')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Deskripsi')),
                ('file', models.FileField(upload_to='%Y/%m/%d', verbose_name='Unggah Berkas')),
                ('uploaded_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Tanggal Unggah')),
            ],
            options={
                'verbose_name_plural': 'Shape Files',
            },
        ),
    ]
