# Generated by Django 4.2.15 on 2024-09-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptkr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bencana',
            name='tanggal_terjadi',
            field=models.DateTimeField(verbose_name='Tanggal terjadi'),
        ),
    ]
