# Generated by Django 4.2.15 on 2024-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptkr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumahterdampak',
            name='dusun',
            field=models.CharField(max_length=150, verbose_name='Dusun'),
        ),
        migrations.AlterField(
            model_name='rumahterdampak',
            name='kecamatan',
            field=models.CharField(max_length=150, verbose_name='Kecamatan'),
        ),
        migrations.AlterField(
            model_name='rumahterdampak',
            name='kelurahan',
            field=models.CharField(max_length=150, verbose_name='Kelurahan'),
        ),
        migrations.AlterField(
            model_name='rumahterdampak',
            name='ket_atap',
            field=models.CharField(max_length=255, verbose_name='Indikasi kerusakan atap'),
        ),
        migrations.AlterField(
            model_name='rumahterdampak',
            name='ket_balok',
            field=models.CharField(max_length=255, verbose_name='Indikasi kerusakan balok'),
        ),
        migrations.AlterField(
            model_name='rumahterdampak',
            name='ket_dinding',
            field=models.CharField(max_length=255, verbose_name='Indikasi kerusakan dinding'),
        ),
        migrations.AlterField(
            model_name='rumahterdampak',
            name='ket_kolom',
            field=models.CharField(max_length=255, verbose_name='Indikasi kerusakan kolom'),
        ),
        migrations.AlterField(
            model_name='rumahterdampak',
            name='ket_pondasi',
            field=models.CharField(max_length=255, verbose_name='Indikasi kerusakan pondasi'),
        ),
        migrations.AlterField(
            model_name='rumahterdampak',
            name='kota',
            field=models.CharField(max_length=150, verbose_name='Kota'),
        ),
        migrations.AlterField(
            model_name='rumahterdampak',
            name='provinsi',
            field=models.CharField(max_length=150, verbose_name='Provinsi'),
        ),
    ]
