# Generated by Django 4.2.15 on 2024-09-03 12:15

from django.db import migrations, models
import ptkr.models.ptkr


class Migration(migrations.Migration):

    dependencies = [
        ('ptkr', '0002_alter_bencana_tanggal_terjadi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumahterdampak',
            name='foto',
            field=models.ImageField(help_text='Ukuran foto maksimal 5MB.', upload_to=ptkr.models.ptkr.RumahTerdampak.file_upload, validators=[ptkr.models.ptkr.file_size, ptkr.models.ptkr.file_extension], verbose_name='Foto sample'),
        ),
    ]
