# Generated by Django 4.2.15 on 2024-08-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptkr', '0003_rumahterdampak_lat_rumahterdampak_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumahterdampak',
            name='ket_plantai',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indikasi kerusakan plat lantai'),
        ),
        migrations.AddField(
            model_name='rumahterdampak',
            name='ket_tangga',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indikasi kerusakan tangga'),
        ),
    ]
